aemsites/888de

.eslintignore, .eslintrc.js, .github/pull_request_template.md, .gitignore, README.md
Test URLs:
- Before:  https://main--888de--aemsites.hlx.live/404.html
- After:  https://readme--888de--aemsites.hlx.live/404.html
=> Readme + dotfiles updates

scripts/aem.js, scripts/scripts.js, styles/fonts.css, styles/styles.css
This change deals with general styles as seen in the majority of the pages, such as https://www.888.de/sicherheit-datenschutz/quelle-der-geldmittel/ .  There will no doubt be many more adjustments to come.
- breakpoints and general body spacing
- body and heading fonts (h1 and h2 for now)
- bullets spacing
- links style
- adding main colors as variables
Also I have added an additional outer DIV around each section, to allow for compound sections that have 100% wide background colors and images.
Fix #2 
- Before: https://main--888de--aemsites.hlx.page/sicherheit-datenschutz/quelle-der-geldmittel
- After: https://2-globalstyles--888de--aemsites.hlx.page/sicherheit-datenschutz/quelle-der-geldmittel
=> 2 - initial global styles added

blocks/columns/columns.css, scripts/aem.js, scripts/scripts.js, styles/fonts.css, styles/styles.css, templates/home/home.css
Fix #19 
- After: https://19-landingpage--888de--aemsites.hlx.page/
Columns styling (white section with the 'award' logos ) - compare with live page at https://www.888.de/
(Ignore carousel content, that is being styled in another branch.)
=> 19 - section metadata, column, home styles

blocks/footer/footer.css, scripts/aem.js, styles/styles.css
Also made some standard color decisions for those that were nearly identical and added to global colors.
Fix #8 
- After: https://8-stickyfooter--888de--aemsites.hlx.page/
Compare the sticky footer links with original site https://www.888.de/sicherheit-datenschutz/betruegerische-emails/
=> 8 - sticky link mobile footer added

blocks/accordion/accordion.css, blocks/carousel/carousel.css, styles/styles.css, templates/inner/inner.css
Fix #43 
- After: https://43-colorcleanup--888de--aemsites.hlx.page/
Compare the colors of the dark grays in the carousel and footer to the live page at 888.de, they should look really close still.
=> color values cleanup

blocks/footer/footer.js, blocks/header/header.css, blocks/header/header.js, scripts/scripts.js, styles/styles.css
Adding login modal 
Fix #53
- Before: https://main--888de--aemsites.hlx.live/drafts/dfink/test-page
- After: https://53-login-modal--888de--aemsites.hlx.live/drafts/dfink/test-page
=> 53 login modal

blocks/header/header.js
- Before: https://main--888de--aemsites.hlx.live/
- After: https://move-login-to-fragments--888de--aemsites.hlx.live/
=> move to fragments

blocks/header/header.js
- After: https://Login-modal-fix--888de--aemsites.hlx.live/
=> Login modal fix

blocks/cards/cards.css, blocks/cards/cards.js, blocks/carousel/carousel.css, scripts/dom-helpers.js, styles/styles.css, templates/inner/inner.css
Fix #50
- Before: https://main--888de--aemsites.hlx.page/banking/
- After: https://50-cards--888de--aemsites.hlx.page/banking/
compare with https://www.888.de/banking/, but NOTE: I am not using the larger body font for this page, I'm keeping it consistent with all the other "inner" pages.
=> finally some cards

scripts/scripts.js
Adding Datalayer Object
Fix #68
- After: https://68-datalayer--888de--aemsites.hlx.live/drafts/dfink/blank-page
1. Make changes to medata.xls, publish and verify that the changes get output to the script element on the page.
=> Adding datalayer function

scripts/delayed.js
Adding GTM
- After: https://gtm-script--888de--aemsites.hlx.live/drafts/dfink/blank-page
=> adding GTM

scripts/delayed.js, scripts/scripts.js
Adding GTM
- After: https://template-fix--888de--aemsites.hlx.live/drafts/dfink/blank-page
=> Template fix - DTM

head.html, scripts/delayed.js, scripts/scripts.js
Converting datalayer to be static
- After: https://datalayer-fix--888de--aemsites.hlx.page/drafts/dfink/blank-page
=> Datalayer fix

blocks/accordion/accordion.css
Fix #81 
- Before: https://main--888de--aemsites.hlx.live/faq-slots-de
- After: https://81-accordionfix--888de--aemsites.hlx.page/faq-slots-de
- - Before: https://main--888de--aemsites.hlx.live/faq-poker-de
- After: https://81-accordionfix--888de--aemsites.hlx.page/faq-poker-de
- Highlight only shows on hover of the question, it no longer stays highlighted. 
- height of the accordion "question" is matching better now
Compare with https://www.888.de/faq-poker-de/
=> 81 - accordion fixes

scripts/delayed.js
- After: https://moving-placement--888de--aemsites.hlx.live/drafts/dfink/blank-page
=> Moving GTM placement

scripts/delayed.js, templates/inner-anchor/inner-anchor.js
- Before: https://main--888de--aemsites.hlx.live/uber-uns
- After: https://inner-anchor-fix-brackets--888de--aemsites.hlx.live/uber-uns
=> Inner anchor fix brackets

scripts/dom-helpers.js, scripts/scripts.js, styles/breadcrumbs.css, templates/inner-anchor/inner-anchor.css, templates/inner-anchor/inner-anchor.js, templates/inner/inner.css, templates/inner/inner.js
Fix #7
- After: https://breadcrumbs--888de--aemsites.hlx.page/uber-uns (one level)
- After: https://breadcrumbs--888de--aemsites.hlx.page/banking/breadcrumb-test (two levels)
- After: https://breadcrumbs--888de--aemsites.hlx.page/banking/breadcrumb-test/breadcrumb-test (three levels)
=> adding breadcrumbs

blocks/cards/cards.css, scripts/dom-helpers.js, scripts/scripts.js, styles/breadcrumbs.css, templates/inner-anchor/inner-anchor.css, templates/inner-anchor/inner-anchor.js, templates/inner/inner.css, templates/inner/inner.js
Fix #80
- Before: https://main--888de--aemsites.hlx.live/aktionen
- After: https://80-card-variant--888de--aemsites.hlx.live/aktionen
=> 80 card variant

styles/styles.css
- After: https://fixing-h2--888de--aemsites.hlx.page/888club/vorteile
- After: https://fixing-h2--888de--aemsites.hlx.page
=> Fixing H2 Issue

blocks/carousel/carousel.js
Fix #115 
- After: https://bug-115--888de--aemsites.hlx.page/
=> Button script

scripts/scripts.js
Minor fix to breadcrumbs
- Before: https://main--888de--aemsites.hlx.page/banking/einzahlung/wie-einzahlen
- After: https://breadcrumb-fix--888de--aemsites.hlx.page/banking/einzahlung/wie-einzahlen
=> Minor fixes

blocks/header/header.css, scripts/scripts.js, templates/inner-anchor/inner-anchor.css, templates/inner-anchor/inner-anchor.js, templates/inner-nav/inner-nav.css, templates/inner-nav/inner-nav.js, templates/inner/inner.js
- fixed left nav collision when viewport height is small - restructured dom
- Fixed header logo size at mobile width
- Optimized code
Fix #105
- Before: https://main--888de--aemsites.hlx.page/sicherheit-datenschutz/nutzungsvereinbarung
- After: https://reworking-inner-templates-breadcrumbs--888de--aemsites.hlx.page/sicherheit-datenschutz/nutzungsvereinbarung
- After: https://reworking-inner-templates-breadcrumbs--888de--aemsites.hlx.page/uber-uns (inner-anchor breadcrumb update)
- After: https://reworking-inner-templates-breadcrumbs--888de--aemsites.hlx.page/banking/ (inner breadcrumb update)
=> Reworking inner templates breadcrumbs

templates/inner-nav/inner-nav.css
- Before: https://main--888de--aemsites.hlx.page/sicherheit-datenschutz/datenschutzrichtlinie
- After: https://right-col-full-width--888de--aemsites.hlx.page/sicherheit-datenschutz/datenschutzrichtlinie
=> fixing full width issue

blocks/carousel/carousel.css, blocks/carousel/carousel.js, scripts/scripts.js
Fix #57
- Before: https://main--888de--aemsites.hlx.live/
- After: https://bug-57--888de--aemsites.hlx.live/
=> Carousel mobile - CLS fix

blocks/header/header.js, scripts/888-main.js, templates/inner-anchor/inner-anchor.js, templates/inner-nav-fragment/inner-nav-fragment.js, templates/inner-nav/inner-nav.js, templates/inner/inner.js
- Reworked header.js to make the nav and login modal load after clicking spending up page load performance.
- Added lint comments to ignore console.log statements that are used for error logging
Fix #130
- Before: https://main--888de--aemsites.hlx.live/
- After: https://130-rework-login--888de--aemsites.hlx.live/
- After: https://130-rework-login--888de--aemsites.hlx.live/drafts/dfink/blank-page
=> Performance update to header.js and added eslint comments to remove warnings

templates/inner-nav-fragment/inner-nav-fragment.js, templates/inner-nav/inner-nav.css
- Fixed issues with active item highlighting on the banking pages
- Fixed console log message when left-nav is not found
Fix #<gh-issue-id>
- Before: https://main--888de--aemsites.hlx.page/banking/abhebung/wie-abheben
- Before: https://main--888de--aemsites.hlx.page/banking/einzahlung/wie-einzahlen
- Before: https://main--888de--aemsites.hlx.page/banking/einzahlung/einzahlungslimits (fixed left-nav height jumping)
- Before: https://main--888de--aemsites.hlx.page/bonusregelungen  (no change - just verify no impact)
- After: https://left-nav-highlifght-fix--888de--aemsites.hlx.page/banking/abhebung/wie-abheben
- After: https://left-nav-highlifght-fix--888de--aemsites.hlx.page/banking/einzahlung/wie-einzahlen
- After: https://left-nav-highlifght-fix--888de--aemsites.hlx.page/banking/einzahlun …
=> Left nav highlifght fix

scripts/scripts.js, templates/clubspage/clubspage.js
- Before: https://main--888de--aemsites.hlx.page/888club
- After: https://feat-move-clubs-index--888de--aemsites.hlx.page/888club
=> fix clubs nav

blocks/footer/footer.js
Fix #149 
- After: https://footertest--888de--aemsites.hlx.page/
footer should look the same as on hlx.live now
=> Footertest

blocks/header/header.css
- After: https://fixing-page-jump--888de--aemsites.hlx.page/
Open the login modal or the left nav.  You'll notice the page doesn't shift.
=> Fixing page jump

blocks/accordion/accordion.js, scripts/delayed.js
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #48 
- Before: https://main--888de--aemsites.hlx.live/
- After: https://48-jsonld--888de--aemsites.hlx.live/
- Before: https://main--888de--aemsites.hlx.live/faq-slots-de
- After: https://48-jsonld--888de--aemsites.hlx.live/faq-slots-de
You should not see a Meta entry in the head for "json-ld" on either of the "after" pages.
=> json ld changes

blocks/footer/footer.css
Fix 207
- After: https://207-footer-bg--888de--aemsites.hlx.page/
=> fixing z-index

tools/sidekick/config.json
Edit button should show on a live page at www.888.de when merged
- After: https://develop--888de--aemsites.hlx.page/
=> sidekick host update

blocks/header/header.js, tools/sidekick/config.json
Testing a PR into develop, after I approved his PR into Main (but did not merge it there).
Fix #122
Before: https://main--888de--aemsites.hlx.page/
After: https://222-nav-icon-alt--888de--aemsites.hlx.page/
=> 222 nav icon alt

404.html, blocks/carousel/carousel.js
Changed <a> to <span> to improve SEO score.
Fix #232 
- After: https://232-seo-improvement--888de--aemsites.hlx.page/
- Ensure that the bouncing-arrow which appears on the mobile view functions the same as it did before.
- after it's been merged we can double check to see that the SEO score has improved
- original score -  https://pagespeed.web.dev/analysis/https-www-888-de/602rpyo0de?form_factor=mobile
=> 232 seo improvement

scripts/scripts.js
Fix 238 
- After: https://238-loadheader--888de--aemsites.hlx.page/
Need to do some LHS testing to see if Speed Index is increased, but other scores not decreased.
=> 238 move loadHeader up sooner

blocks/carousel/carousel.js
- Before: https://develop--888de--aemsites.hlx.page/
- After: https://carousel-revert--888de--aemsites.hlx.page/
=> Revert "Lhs/carousel (#242)"

sitemap-index.xml
Forgot to commit the actual file in the last pr.
- After: https://247-sitemapfile--888de--aemsites.hlx.page/
Adding external sitemap-index location per docs https://www.aem.live/developer/sitemap#initial-sitemap-configuration
=> adding sitemap-index file this time
